alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit '
alias gd='git diff'
alias gds='git diff --staged'
alias gk='gitk --all&'
alias gb='git branch '
alias gl='git log --pretty=format:"%h: %ad: %an: %s" --date=short'
alias gco='git checkout '
alias go='git checkout '
alias gg='git grep -En '
# alias gx='gitx --all'

